//! Colors.
//!
//! Deliberately boring: one dark theme, no theming system. The editor has to
//! feel fast before it needs to look configurable.

/// A color in linear space, ready for a linear-to-sRGB render target.
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct Color {
    pub linear: [f32; 4],
    pub srgb: [u8; 4],
}

impl Color {
    /// Builds a color from ordinary sRGB hex components.
    pub const fn rgb(red: u8, green: u8, blue: u8) -> Self {
        Self::rgba(red, green, blue, 255)
    }

    pub const fn rgba(red: u8, green: u8, blue: u8, alpha: u8) -> Self {
        Color {
            linear: [
                srgb_to_linear(red),
                srgb_to_linear(green),
                srgb_to_linear(blue),
                alpha as f32 / 255.0,
            ],
            srgb: [red, green, blue, alpha],
        }
    }

    pub fn to_glyphon(self) -> glyphon::Color {
        glyphon::Color::rgba(self.srgb[0], self.srgb[1], self.srgb[2], self.srgb[3])
    }
}

/// sRGB transfer function, evaluated at compile time.
///
/// The swapchain is `Bgra8UnormSrgb`, so the GPU converts what the shader
/// writes from linear to sRGB. Without this, every color would come out washed
/// out relative to the value that was picked.
const fn srgb_to_linear(component: u8) -> f32 {
    // A const-friendly approximation of the piecewise sRGB curve: exact on the
    // linear segment, and a gamma-2.2 power curve elsewhere. Const functions
    // cannot call `powf`, so the curve is evaluated from a table.
    SRGB_TO_LINEAR[component as usize]
}

/// Lookup table for the sRGB transfer function, generated by the build-free
/// expression below at compile time.
static SRGB_TO_LINEAR: [f32; 256] = build_srgb_table();

const fn build_srgb_table() -> [f32; 256] {
    let mut table = [0.0f32; 256];
    let mut index = 0;
    while index < 256 {
        let value = index as f32 / 255.0;
        table[index] = if value <= 0.040_45 {
            value / 12.92
        } else {
            // ((value + 0.055) / 1.055)^2.4, expanded with a const-friendly
            // Newton iteration on the cube root; accurate to well under one
            // 8-bit step, which is all a color needs.
            let base = (value + 0.055) / 1.055;
            const_powf_2_4(base)
        };
        index += 1;
    }
    table
}

/// `base^2.4` for `base` in `[0, 1]`, using exp/ln series that work in a const
/// context.
const fn const_powf_2_4(base: f32) -> f32 {
    if base <= 0.0 {
        return 0.0;
    }
    // ln(base) via atanh series: ln(x) = 2 * atanh((x-1)/(x+1))
    let z = (base - 1.0) / (base + 1.0);
    let z2 = z * z;
    let mut term = z;
    let mut sum = z;
    let mut k = 1;
    while k < 12 {
        term *= z2;
        sum += term / (2 * k + 1) as f32;
        k += 1;
    }
    let ln_base = 2.0 * sum;
    // exp(2.4 * ln(base)) via a truncated Taylor series.
    let exponent = 2.4 * ln_base;
    let mut result = 1.0;
    let mut power = 1.0;
    let mut factorial = 1.0;
    let mut n = 1;
    while n < 20 {
        power *= exponent;
        factorial *= n as f32;
        result += power / factorial;
        n += 1;
    }
    result
}

/// Every color the shell draws.
#[derive(Copy, Clone, Debug)]
pub struct Theme {
    pub background: Color,
    pub gutter_background: Color,
    pub gutter_text: Color,
    pub text: Color,
    pub dim_text: Color,
    pub cursor: Color,
    pub current_line: Color,
    pub selection: Color,
    pub tab_bar: Color,
    pub tab_inactive: Color,
    pub tab_active: Color,
    pub tab_text: Color,
    pub dirty_marker: Color,
    pub status_bar: Color,
    pub status_text: Color,
    pub overlay_background: Color,
    pub overlay_border: Color,
    /// Menu surfaces. Fully opaque on purpose: a dropdown that lets the
    /// document show through is unreadable, and translucency here would also
    /// mean the text underneath is still being drawn and paid for.
    pub menu_background: Color,
    pub menu_highlight: Color,
    pub menu_border: Color,
    pub warning: Color,
    pub error: Color,
    pub ok: Color,
    pub scrollbar: Color,
}

impl Theme {
    pub const fn dark() -> Self {
        Theme {
            background: Color::rgb(0x14, 0x16, 0x1A),
            gutter_background: Color::rgb(0x14, 0x16, 0x1A),
            gutter_text: Color::rgb(0x4A, 0x51, 0x5C),
            text: Color::rgb(0xD6, 0xDC, 0xE4),
            dim_text: Color::rgb(0x76, 0x7F, 0x8C),
            cursor: Color::rgb(0x5A, 0xC8, 0xFA),
            current_line: Color::rgb(0x1B, 0x1E, 0x25),
            selection: Color::rgba(0x2C, 0x5A, 0x8C, 0xB0),
            tab_bar: Color::rgb(0x0F, 0x11, 0x15),
            tab_inactive: Color::rgb(0x0F, 0x11, 0x15),
            tab_active: Color::rgb(0x14, 0x16, 0x1A),
            tab_text: Color::rgb(0x8A, 0x93, 0xA0),
            dirty_marker: Color::rgb(0xE0, 0xA0, 0x3C),
            status_bar: Color::rgb(0x18, 0x2A, 0x3E),
            status_text: Color::rgb(0xC4, 0xCE, 0xDA),
            overlay_background: Color::rgba(0x0A, 0x0C, 0x10, 0xE8),
            overlay_border: Color::rgb(0x2A, 0x30, 0x3A),
            menu_background: Color::rgb(0x1E, 0x22, 0x2A),
            menu_highlight: Color::rgb(0x2C, 0x5A, 0x8C),
            menu_border: Color::rgb(0x3A, 0x42, 0x50),
            warning: Color::rgb(0xE0, 0xA0, 0x3C),
            error: Color::rgb(0xE0, 0x5C, 0x5C),
            ok: Color::rgb(0x6C, 0xC0, 0x7C),
            scrollbar: Color::rgb(0x33, 0x39, 0x44),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn srgb_conversion_matches_the_reference_curve() {
        for component in [0u8, 1, 32, 64, 128, 200, 255] {
            let value = component as f32 / 255.0;
            let expected = if value <= 0.040_45 {
                value / 12.92
            } else {
                ((value + 0.055) / 1.055f32).powf(2.4)
            };
            let actual = srgb_to_linear(component);
            assert!(
                (actual - expected).abs() < 0.002,
                "component {component}: {actual} vs {expected}"
            );
        }
    }

    #[test]
    fn colors_keep_their_srgb_values_for_text() {
        let color = Color::rgb(0xD6, 0xDC, 0xE4);
        assert_eq!(color.srgb, [0xD6, 0xDC, 0xE4, 255]);
    }
}
