//! Colors.
//!
//! Deliberately boring: one dark theme, no theming system. The editor has to
//! feel fast before it needs to look configurable.
//!
//! The palette itself is not invented here: it is Lapce's own `Dark` theme,
//! pulled from `defaults/dark-theme.toml` in the Lapce repository (One Dark's
//! base sixteen colors, in Lapce's own `[color-theme.ui]` role assignments).
//! LightSpeed's UI layout is a deliberate copy of Lapce's, and a copied
//! layout in a different palette would still look like a different program.

/// A color in linear space, ready for a linear-to-sRGB render target.
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct Color {
    pub linear: [f32; 4],
    pub srgb: [u8; 4],
}

impl Color {
    /// Builds a color from ordinary sRGB hex components.
    pub const fn rgb(red: u8, green: u8, blue: u8) -> Self {
        Self::rgba(red, green, blue, 255)
    }

    pub const fn rgba(red: u8, green: u8, blue: u8, alpha: u8) -> Self {
        Color {
            linear: [
                srgb_to_linear(red),
                srgb_to_linear(green),
                srgb_to_linear(blue),
                alpha as f32 / 255.0,
            ],
            srgb: [red, green, blue, alpha],
        }
    }

    pub fn to_glyphon(self) -> glyphon::Color {
        glyphon::Color::rgba(self.srgb[0], self.srgb[1], self.srgb[2], self.srgb[3])
    }
}

/// sRGB transfer function, evaluated at compile time.
///
/// The swapchain is `Bgra8UnormSrgb`, so the GPU converts what the shader
/// writes from linear to sRGB. Without this, every color would come out washed
/// out relative to the value that was picked.
const fn srgb_to_linear(component: u8) -> f32 {
    // A const-friendly approximation of the piecewise sRGB curve: exact on the
    // linear segment, and a gamma-2.2 power curve elsewhere. Const functions
    // cannot call `powf`, so the curve is evaluated from a table.
    SRGB_TO_LINEAR[component as usize]
}

/// Lookup table for the sRGB transfer function, generated by the build-free
/// expression below at compile time.
static SRGB_TO_LINEAR: [f32; 256] = build_srgb_table();

const fn build_srgb_table() -> [f32; 256] {
    let mut table = [0.0f32; 256];
    let mut index = 0;
    while index < 256 {
        let value = index as f32 / 255.0;
        table[index] = if value <= 0.040_45 {
            value / 12.92
        } else {
            // ((value + 0.055) / 1.055)^2.4, expanded with a const-friendly
            // Newton iteration on the cube root; accurate to well under one
            // 8-bit step, which is all a color needs.
            let base = (value + 0.055) / 1.055;
            const_powf_2_4(base)
        };
        index += 1;
    }
    table
}

/// `base^2.4` for `base` in `[0, 1]`, using exp/ln series that work in a const
/// context.
const fn const_powf_2_4(base: f32) -> f32 {
    if base <= 0.0 {
        return 0.0;
    }
    // ln(base) via atanh series: ln(x) = 2 * atanh((x-1)/(x+1))
    let z = (base - 1.0) / (base + 1.0);
    let z2 = z * z;
    let mut term = z;
    let mut sum = z;
    let mut k = 1;
    while k < 12 {
        term *= z2;
        sum += term / (2 * k + 1) as f32;
        k += 1;
    }
    let ln_base = 2.0 * sum;
    // exp(2.4 * ln(base)) via a truncated Taylor series.
    let exponent = 2.4 * ln_base;
    let mut result = 1.0;
    let mut power = 1.0;
    let mut factorial = 1.0;
    let mut n = 1;
    while n < 20 {
        power *= exponent;
        factorial *= n as f32;
        result += power / factorial;
        n += 1;
    }
    result
}

/// Every color the shell draws.
#[derive(Copy, Clone, Debug)]
pub struct Theme {
    pub background: Color,
    pub gutter_background: Color,
    pub gutter_text: Color,
    pub text: Color,
    pub dim_text: Color,
    pub cursor: Color,
    pub current_line: Color,
    pub selection: Color,
    /// Every find match, dimmer than the selection so the current one (drawn
    /// as a normal selection on top of this) still reads as "the one you're
    /// on".
    pub search_match: Color,
    pub syntax_keyword: Color,
    pub syntax_string: Color,
    pub syntax_comment: Color,
    pub syntax_number: Color,
    pub tab_bar: Color,
    pub tab_inactive: Color,
    pub tab_active: Color,
    pub tab_text: Color,
    pub dirty_marker: Color,
    pub status_bar: Color,
    pub status_text: Color,
    pub overlay_background: Color,
    pub overlay_border: Color,
    /// The explorer / search / git-status sidebar. A real docked panel, so
    /// it gets its own opaque surface rather than borrowing the overlay's
    /// translucent one.
    pub sidebar_background: Color,
    pub sidebar_border: Color,
    pub sidebar_selected: Color,
    /// A lighter touch than `sidebar_selected`, for the row under the
    /// pointer that is not (yet) the selection.
    pub sidebar_hover: Color,
    /// Directory rows in the explorer -- a distinct tint standing in for the
    /// folder icon VS Code draws, since this renderer has no icons.
    pub sidebar_folder: Color,
    /// Menu surfaces. Fully opaque on purpose: a dropdown that lets the
    /// document show through is unreadable, and translucency here would also
    /// mean the text underneath is still being drawn and paid for.
    pub menu_background: Color,
    pub menu_highlight: Color,
    pub menu_border: Color,
    pub warning: Color,
    pub error: Color,
    pub ok: Color,
    pub scrollbar: Color,
    /// The activity bar: the narrow icon rail (Explorer / Search / Source
    /// Control / ...) at the very left edge, Lapce's `activity.*`.
    pub activity_background: Color,
    /// The active item's column reads as "cut into" the editor rather than
    /// highlighted on top of it -- it shares the editor's own background.
    pub activity_current: Color,
    pub activity_icon_active: Color,
    pub activity_icon_inactive: Color,
    /// Lapce draws tabs flat, with a thin colored underline marking the
    /// active one, rather than filling the whole tab with a different
    /// background the way the previous VS-Code-ish style did.
    pub tab_underline_active: Color,
    pub tab_underline_inactive: Color,
    /// Hover feedback shared by the activity bar and any docked panel's own
    /// icon rail (the bottom panel's terminal/search/problems switcher).
    pub panel_hovered: Color,
}

/// What kind of row a sidebar line is, for coloring it -- the closest this
/// text-only renderer gets to VS Code's folder/file icons.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SidebarRowKind {
    /// The panel's title row (e.g. "Explorer", "Search Results").
    Header,
    Directory,
    File,
    /// A message with no action of its own: "(empty)", "Searching...", "No
    /// matches for...", and so on.
    Info,
}

impl Theme {
    pub fn syntax_color(&self, kind: ls_core::TokenKind) -> Color {
        match kind {
            ls_core::TokenKind::Keyword => self.syntax_keyword,
            ls_core::TokenKind::String => self.syntax_string,
            ls_core::TokenKind::Comment => self.syntax_comment,
            ls_core::TokenKind::Number => self.syntax_number,
        }
    }

    pub fn sidebar_row_color(&self, kind: SidebarRowKind) -> Color {
        match kind {
            SidebarRowKind::Header => self.dim_text,
            SidebarRowKind::Directory => self.sidebar_folder,
            SidebarRowKind::File => self.text,
            SidebarRowKind::Info => self.dim_text,
        }
    }

    pub const fn dark() -> Self {
        // Lapce's `[color-theme.base]` sixteen colors (One Dark), named here
        // the way the TOML names them so the mapping below is checkable
        // against the source at a glance.
        const BLACK: Color = Color::rgb(0x28, 0x2C, 0x34); // primary-background
        const SECONDARY_BACKGROUND: Color = Color::rgb(0x21, 0x25, 0x2B);
        const CURRENT_BACKGROUND: Color = Color::rgb(0x2C, 0x31, 0x3A);
        const WHITE: Color = Color::rgb(0xAB, 0xB2, 0xBF); // text
        const DIM_TEXT: Color = Color::rgb(0x5C, 0x63, 0x70);
        const GREEN: Color = Color::rgb(0x98, 0xC3, 0x79);
        const GREY: Color = Color::rgb(0x3E, 0x44, 0x51);
        const PURPLE: Color = Color::rgb(0xC6, 0x78, 0xDD);
        const ORANGE: Color = Color::rgb(0xD1, 0x9A, 0x66);
        const RED: Color = Color::rgb(0xE0, 0x6C, 0x75);
        const YELLOW: Color = Color::rgb(0xE5, 0xC0, 0x7B);
        const CARET: Color = Color::rgb(0x52, 0x8B, 0xFF); // editor.caret

        Theme {
            background: BLACK, // editor.background
            gutter_background: BLACK,
            gutter_text: DIM_TEXT,
            text: WHITE,        // editor.foreground
            dim_text: DIM_TEXT, // editor.dim
            cursor: CARET,
            current_line: Color::rgb(0x2C, 0x31, 0x3C), // editor.current_line
            selection: GREY,                            // editor.selection
            search_match: Color::rgba(0xE5, 0xC0, 0x7B, 0x60),
            // Syntax roles from `[color-theme.syntax]`.
            syntax_keyword: PURPLE,
            syntax_string: GREEN,
            syntax_comment: DIM_TEXT,
            syntax_number: YELLOW,
            // Lapce draws tabs flat with an underline, not a filled block;
            // both tab states share one background and differ only by the
            // underline color (see `tab_underline_*` below).
            tab_bar: SECONDARY_BACKGROUND,
            tab_inactive: SECONDARY_BACKGROUND, // lapce.tab.inactive.background
            tab_active: BLACK,                  // lapce.tab.active.background
            tab_text: WHITE,
            dirty_marker: ORANGE,
            status_bar: SECONDARY_BACKGROUND, // status.background
            status_text: WHITE,               // status.foreground
            overlay_background: Color::rgba(0x21, 0x25, 0x2B, 0xE8),
            overlay_border: Color::rgb(0x00, 0x00, 0x00), // lapce.border
            sidebar_background: SECONDARY_BACKGROUND,     // panel.background
            sidebar_border: Color::rgb(0x00, 0x00, 0x00),
            sidebar_selected: CURRENT_BACKGROUND, // panel.current.background
            sidebar_hover: Color::rgb(0x34, 0x3A, 0x45), // panel.hovered.background
            sidebar_folder: ORANGE,
            // Bound as literal `Color::rgb(...)` rather than the named
            // constants above (even though the values are the same ones):
            // an architecture test greps this file's source for exactly
            // that pattern on these three fields, so a translucent
            // `Color::rgba` can never sneak into a dropdown surface.
            menu_background: Color::rgb(0x21, 0x25, 0x2B), // palette.background
            menu_highlight: Color::rgb(0x2C, 0x31, 0x3A),  // palette.current.background
            menu_border: Color::rgb(0x00, 0x00, 0x00),
            warning: YELLOW, // lapce.warn
            error: RED,      // lapce.error
            ok: GREEN,
            scrollbar: Color::rgba(0x3E, 0x44, 0x51, 0xBB), // lapce.scroll_bar
            activity_background: SECONDARY_BACKGROUND,      // activity.background
            activity_current: BLACK,                        // activity.current
            activity_icon_active: WHITE,                    // lapce.icon.active
            activity_icon_inactive: DIM_TEXT,               // lapce.icon.inactive
            tab_underline_active: CARET,                    // lapce.tab.active.underline
            tab_underline_inactive: Color::rgba(0x52, 0x8B, 0xFF, 0x77),
            panel_hovered: Color::rgb(0x34, 0x3A, 0x45),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn srgb_conversion_matches_the_reference_curve() {
        for component in [0u8, 1, 32, 64, 128, 200, 255] {
            let value = component as f32 / 255.0;
            let expected = if value <= 0.040_45 {
                value / 12.92
            } else {
                ((value + 0.055) / 1.055f32).powf(2.4)
            };
            let actual = srgb_to_linear(component);
            assert!(
                (actual - expected).abs() < 0.002,
                "component {component}: {actual} vs {expected}"
            );
        }
    }

    #[test]
    fn colors_keep_their_srgb_values_for_text() {
        let color = Color::rgb(0xD6, 0xDC, 0xE4);
        assert_eq!(color.srgb, [0xD6, 0xDC, 0xE4, 255]);
    }
}
